# Use new container infrastructure to enable caching
sudo: false

language: java

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

matrix:
  include:
    - env: BUILD=stack ARGS="--resolver lts-6.6"
      addons: {apt: {packages: [libgmp-dev, oracle-java8-installer]}}
      os: linux
      compiler: ": #stack 7.10.3 linux"
    - env: BUILD=stack ARGS="--resolver lts-6.6"
      compiler: ": #stack 7.10.3 osx"
      osx_image: xcode8
      os: osx

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

# We want to always allow newer versions of packages when building on GHC HEAD
- CABALARGS=""
- if [ "x$GHCVER" = "xhead" ]; then CABALARGS=--allow-newer; fi

# Download and unpack the stack executable
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

  # Use the more reliable S3 mirror of Hackage
  mkdir -p $HOME/.cabal
  echo 'remote-repo: hackage.haskell.org:http://hackage.fpcomplete.com/' > $HOME/.cabal/config
  echo 'remote-repo-cache: $HOME/.cabal/packages' >> $HOME/.cabal/config

  if [ "$CABALVER" != "1.16" ]
  then
    echo 'jobs: $ncpus' >> $HOME/.cabal/config
  fi

install:
# Build dependencies
- stack --no-terminal --install-ghc test --only-dependencies
- travis_wait 30 ./install.sh

script:
# Build the package, its tests, and its docs and run the tests
- cd tests/verify/
- ./verify.sh
- |
  if [ `uname` != "Darwin"]
  then
    cd ../packages/
    ./Test.hs
  fi
